apiVersion: v1
kind: Secret
metadata:
  name: fin-enterprise-api-secrets
stringData:
  DATABASE_URL: postgresql+asyncpg://finenterprise:fin_enterprise_secret@postgres.fin-enterprise-local.svc:5432/fin_enterprise_assets
