all:
  children:
    fin_enterprise_api:
      hosts:
        api-vm-01:
          ansible_host: 10.1.10.50
        api-vm-02:
          ansible_host: 10.1.10.51
      vars:
        ansible_user: ubuntu
        app_image: docker.io/financial-enterprise/asset-api:latest
        app_port: 8000
