apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fin-enterprise-api
spec:
  selector:
    matchLabels:
      app: fin-enterprise-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
